#!/bin/bash

# Compile C++ code for a problem
# For help, pass in -h or --help
# To compile a program, pass in the year followed by the problem number
# For an example, ./compile 2019 J1
# To execute the compiled program, pass in -e or --exec

argString="$*" # Passed in arguments
IFS=" " read -ra args <<< "$argString" # Assign args variable from argv

inputFile="" # Input file name for later
bin="bin" # Binary output file
compiler="clang++" # Default compiler
checksumCmd="openssl" # Default checksum command
checksumAlgo="sha3-384" # Default checksum algorithm

# If -h or --help flags are passed
if [[ "${args[*]}" =~ "-h" ]]||[[ "${args[*]}" =~ "--help" ]]||[[ ${#args[@]} == 0 ]]; then
    printf "Compile C++ code for a problem

To compile a program, pass in the year followed by the problem number
    e.g ./compile.bash 2020 S1

-h --help help for command
-e --exec execute binary file right after compiling
    "
    exit 0
fi

for file in "${args[0]}"/*; do # For each file in directory (args[0], the contest year)

    # If file matches the problem number (e.g J1) and has "cpp" in its name
    if [[ "$file" == *"${args[1]}"* ]]&&[[ "$file" == *"cpp"* ]]; then
        inputFile="$file"
        break
    fi

done

if [[ "$inputFile" == "" ]]; then # If no input file exists
    echo "Cannot file for problem ${args[*]}"
    exit 1
fi

if [[ ! "$(clang++ --version)" ]]; then
    echo "clang++ not found; changing compiler to g++"
    compiler="g++"
fi

if [[ ! "$(g++ --version)" ]]; then
    echo "g++ not found, exiting"
    exit 1
fi

if [[ ! "$(openssl version)" ]]; then
    echo "openssl not found; changing checksum command to shasum"
    checksumCmd="shasum"
    checksumAlgo="-a 384"
fi

if [[ ! "$(shasum --version)" ]]; then
    echo "shasum not found, exiting"
    exit 1
fi

if [[ $("$checksumCmd" "$checksumAlgo" "$inputFile" | node buildInfo.js) == 1 ]]; then
    echo "$compiler $inputFile -o $bin --std=c++11"
    "$compiler" "$inputFile" -o "$bin" --std=c++11 || exit 1
    echo "Compiled!"
else
    echo "No changes were made to $inputFile"
fi


# If -e or --exec flags are passed
if [[ "${args[*]}" =~ "-e" ]]||[[ "${args[*]}" =~ "--exec" ]]; then
    if test -f "$bin"; then
        dashes="---------------"
        printf "Executing\n\nProgram output:\n%s\n" $dashes
        ./"$bin"
        echo -e "\n$dashes"
    else
        echo "$bin does not exist"
    fi
fi
